spring.application.name=tracking

# database
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=${SPRING_DATASOURCE_URL}?sslmode=require&channelBinding=require
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

# hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# external api
config.api.url=${API_URL}
config.api.key=${API_KEY}

# email
brevo.api.url=https://api.brevo.com/v3
brevo.api.key=${BREVO_API_KEY}
brevo.sender.email=${BREVO_SENDER_EMAIL}
brevo.sender.name=Tracking API

# scheduler
scheduler.interval=86400000

# Configuração hikariCP para o Neon
# Tempo máximo de vida de uma conexão — 5 minutos
spring.datasource.hikari.max-lifetime=300000

# Envia um ping keepalive a cada 2 minutos para manter a conexão viva
spring.datasource.hikari.keepalive-time=120000

# Tempo máximo de espera por uma conexão do pool
spring.datasource.hikari.connection-timeout=30000

# Mantém mínimo de conexões idle no pool
spring.datasource.hikari.minimum-idle=1

# Tempo máximo que uma conexão pode ficar idle — 3 minutos
spring.datasource.hikari.idle-timeout=180000